'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync, execFileSync, exec, execFile } = require('child_process');

function execFileSafe(cmd, args) {
  // Fire-and-forget: wt.exe / powershell.exe detach immediately, we only care
  // that the Windows process was kicked off. Errors are logged, never thrown.
  execFile(cmd, args, (err) => {
    if (err) termLog('ERROR', `${cmd} failed: ${err.message}`);
  });
}

// Run cmux CLI command via osascript — needed because codedash runs as a detached server
// and cmux rejects direct socket connections from processes not inside a cmux terminal
function cmuxExec(args) {
  const escaped = args.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return execSync(`osascript -e 'do shell script "cmux ${escaped}"'`, { encoding: 'utf8', timeout: 5000 }).trim();
}

// ── WSL detection ───────────────────────────────────────────

let _wslCache = null;
function isWSL() {
  if (_wslCache !== null) return _wslCache;
  if (process.platform !== 'linux') { _wslCache = false; return false; }
  if (process.env.WSL_DISTRO_NAME || process.env.WSL_INTEROP) { _wslCache = true; return true; }
  try {
    const v = fs.readFileSync('/proc/version', 'utf8');
    _wslCache = /microsoft|WSL/i.test(v);
  } catch { _wslCache = false; }
  return _wslCache;
}

function wslDistro() {
  return process.env.WSL_DISTRO_NAME || '';
}

// Accept only conservative ID characters. Used for anything that flows into a
// filename, window title or resume command argument. All five supported agents
// use IDs that fit this regex (UUIDs, slugs, integers).
const SAFE_SESSION_ID = /^[A-Za-z0-9._-]{1,128}$/;

function assertSafeSessionId(sessionId) {
  if (!SAFE_SESSION_ID.test(String(sessionId || ''))) {
    throw new Error(`Invalid session id: ${JSON.stringify(sessionId)}`);
  }
}

// Tag used as top-level window title so focusTerminalByPid can locate the
// window later via EnumWindows.
function sessionTag(sessionId) {
  return 'codedash-' + String(sessionId).slice(0, 12);
}

// A session is "Windows-side" if its cwd looks like a Windows path
// (drive letter or backslashes) or lives under /mnt/<drive>/... from WSL.
function isWindowsSidePath(p) {
  if (!p) return false;
  if (/^[A-Za-z]:[\\/]/.test(p)) return true;
  if (p.includes('\\')) return true;
  if (/^\/mnt\/[a-z]\//i.test(p)) return true;
  return false;
}

// Translate /mnt/c/Users/foo → C:\Users\foo. Windows-format paths pass through.
function toWindowsPath(p) {
  if (!p) return '';
  if (/^[A-Za-z]:[\\/]/.test(p) || p.includes('\\')) return p.replace(/\//g, '\\');
  const m = p.match(/^\/mnt\/([a-z])\/(.*)$/i);
  if (m) return m[1].toUpperCase() + ':\\' + m[2].replace(/\//g, '\\');
  try {
    return execSync(`wslpath -w ${JSON.stringify(p)}`, { encoding: 'utf8', timeout: 2000 }).trim();
  } catch {
    return p;
  }
}

// Write the resume command to a .sh file in a private temp directory to avoid
// nested quoting through wt.exe / cmd.exe / powershell.exe / wsl.exe / bash,
// and to isolate each launch from client-controlled filename tricks.
function writeWslLaunchScript(fullCmd) {
  const baseDir = fs.mkdtempSync(path.join(os.tmpdir(), 'codedash-launch-'));
  const file = path.join(baseDir, 'launch.sh');
  const body = [
    '#!/bin/bash -l',
    '# Auto-generated by codedash — safe to delete',
    fullCmd,
    'echo',
    'echo "[codedash] session finished — press Enter to close, or keep this shell."',
    'exec bash -l',
    '',
  ].join('\n');
  fs.writeFileSync(file, body, { mode: 0o755 });
  return { file, dir: baseDir };
}

// ── Detect available terminals ──────────────────────────────

function detectTerminals() {
  const terminals = [];
  const platform = process.platform;

  if (platform === 'darwin') {
    // Check iTerm2
    try {
      execSync('osascript -e \'application id "com.googlecode.iterm2"\'', { stdio: 'pipe' });
      terminals.push({ id: 'iterm2', name: 'iTerm2', available: true });
    } catch {
      terminals.push({ id: 'iterm2', name: 'iTerm2', available: false });
    }
    // Terminal.app always available on macOS
    terminals.push({ id: 'terminal', name: 'Terminal.app', available: true });
    // Check Warp
    try {
      const warpInstalled = fs.existsSync('/Applications/Warp.app');
      terminals.push({ id: 'warp', name: 'Warp', available: warpInstalled });
    } catch {
      terminals.push({ id: 'warp', name: 'Warp', available: false });
    }
    // Check Kitty
    try {
      execSync('which kitty', { stdio: 'pipe' });
      terminals.push({ id: 'kitty', name: 'Kitty', available: true });
    } catch {}
    // Check Alacritty
    try {
      execSync('which alacritty', { stdio: 'pipe' });
      terminals.push({ id: 'alacritty', name: 'Alacritty', available: true });
    } catch {}
    // Check cmux
    try {
      if (fs.existsSync('/Applications/cmux.app')) {
        terminals.push({ id: 'cmux', name: 'cmux', available: true });
      }
    } catch {}
  } else if (platform === 'linux' && isWSL()) {
    // WSL: launch Windows-side terminals via wsl.exe so the UI in the Windows
    // browser can spawn a new console on the host and keep the CLI agent in WSL.
    const wslTerms = [
      { id: 'wsl-windows-terminal', name: 'Windows Terminal (wt.exe)', cmd: 'wt.exe' },
      { id: 'wsl-powershell', name: 'PowerShell (powershell.exe)', cmd: 'powershell.exe' },
    ];
    for (const t of wslTerms) {
      try {
        execSync(`which ${t.cmd}`, { stdio: 'pipe' });
        terminals.push({ id: t.id, name: t.name, available: true });
      } catch {
        terminals.push({ id: t.id, name: t.name, available: false });
      }
    }
  } else if (platform === 'linux') {
    // Detect system default terminal (x-terminal-emulator symlink)
    try {
      const defaultBin = execSync('readlink -f $(which x-terminal-emulator) 2>/dev/null', { encoding: 'utf8' }).trim();
      if (defaultBin) {
        terminals.push({ id: defaultBin, name: 'System Default (' + path.basename(defaultBin) + ')', available: true });
      }
    } catch {}
    // Scan for known terminals as suggestions
    const knownBins = [
      'gnome-terminal', 'konsole', 'kitty', 'alacritty', 'wezterm',
      'terminator', 'tilix', 'xfce4-terminal', 'mate-terminal', 'foot', 'xterm',
    ];
    for (const cmd of knownBins) {
      try {
        const fullPath = execSync(`which ${cmd} 2>/dev/null`, { encoding: 'utf8' }).trim();
        if (fullPath && !terminals.find(t => t.id === fullPath)) {
          terminals.push({ id: fullPath, name: cmd, available: true });
        }
      } catch {}
    }
  } else {
    terminals.push({ id: 'cmd', name: 'Command Prompt', available: true });
    terminals.push({ id: 'powershell', name: 'PowerShell', available: true });
    try {
      execSync('where wt', { stdio: 'pipe' });
      terminals.push({ id: 'windows-terminal', name: 'Windows Terminal', available: true });
    } catch {}
  }

  return terminals;
}

// ── Terminal launch ─────────────────────────────────────────

function termLog(tag, msg) {
  const ts = new Date().toLocaleTimeString('en-GB');
  const color = tag === 'ERROR' ? '\x1b[31m' : '\x1b[35m';
  console.log(`  ${color}${ts} [${tag}]\x1b[0m ${msg}`);
}

function openInTerminal(sessionId, tool, flags, projectDir, terminalId) {
  const skipPerms = flags.includes('skip-permissions');
  let cmd;

  if (tool === 'codex') {
    cmd = `codex resume ${sessionId}`;
  } else if (tool === 'qwen') {
    cmd = `qwen -r ${sessionId}`;
  } else if (tool === 'kilo') {
    cmd = `kilo resume ${sessionId}`;
  } else {
    cmd = `claude --resume ${sessionId}`;
    if (skipPerms) cmd += ' --dangerously-skip-permissions';
  }

  const cdPart = projectDir ? `cd ${JSON.stringify(projectDir)} && ` : '';
  const fullCmd = cdPart + cmd;
  const escapedCmd = fullCmd.replace(/"/g, '\\"');
  termLog('TERM', `openInTerminal: terminal=${terminalId || 'default'} tool=${tool} cmd="${fullCmd}"`);

  const platform = process.platform;

  if (platform === 'darwin') {
    switch (terminalId) {
      case 'terminal':
        execSync(`osascript -e 'tell application "Terminal"
          activate
          do script "${escapedCmd}"
        end tell'`);
        break;
      case 'warp': {
        // Warp Launch Configurations API — write temp YAML, open via URI scheme
        const warpConfigDir = path.join(os.homedir(), '.warp', 'launch_configurations');
        const warpConfigName = `codedash-${Date.now()}`;
        const warpConfigPath = path.join(warpConfigDir, `${warpConfigName}.yaml`);
        fs.mkdirSync(warpConfigDir, { recursive: true });
        const warpYaml = [
          '---',
          `name: ${warpConfigName}`,
          'windows:',
          '  - tabs:',
          '      - layout:',
          `          cwd: "${projectDir || ''}"`,
          '          commands:',
          `            - exec: "${cmd.replace(/"/g, '\\"')}"`,
        ].join('\n') + '\n';
        fs.writeFileSync(warpConfigPath, warpYaml);
        try {
          execSync(`open "warp://launch/${warpConfigName}"`, { stdio: 'pipe', timeout: 3000 });
        } catch {
          // Fallback to Terminal.app
          execSync(`osascript -e 'tell application "Terminal" to do script "${escapedCmd}"'`);
        }
        setTimeout(() => { try { fs.unlinkSync(warpConfigPath); } catch {} }, 3000);
        break;
      }
      case 'kitty':
        exec(`kitty --single-instance bash -c '${fullCmd}; exec bash'`);
        break;
      case 'alacritty':
        exec(`alacritty -e bash -c '${fullCmd}; exec bash'`);
        break;
      case 'cmux': {
        // cmux — open new workspace with resume command, then switch to it
        try {
          const cwdArg = projectDir ? ` --cwd ${JSON.stringify(projectDir)}` : '';
          const cmdArg = ` --command ${JSON.stringify(cmd)}`;
          const out = cmuxExec(`new-workspace${cwdArg}${cmdArg}`);
          const wsMatch = out.match(/workspace:\d+/);
          if (wsMatch) {
            cmuxExec(`select-workspace --workspace ${wsMatch[0]}`);
          }
          execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
        } catch {
          execSync(`osascript -e 'tell application "cmux" to activate'`);
        }
        break;
      }
      case 'iterm2':
      default: {
        const script = `
          tell application "iTerm"
            activate
            set newWindow to (create window with default profile)
            tell current session of newWindow
              write text "${escapedCmd}"
            end tell
          end tell
        `;
        try {
          execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { stdio: 'pipe' });
        } catch {
          // Fallback to Terminal.app
          execSync(`osascript -e 'tell application "Terminal" to do script "${escapedCmd}"'`);
        }
        break;
      }
    }
  } else if (platform === 'linux' && isWSL()) {
    assertSafeSessionId(sessionId);
    const tag = sessionTag(sessionId);
    const tid = terminalId || 'wsl-windows-terminal';
    const winSide = isWindowsSidePath(projectDir);
    termLog('TERM', `WSL launch: winSide=${winSide} terminal=${tid}`);

    if (winSide) {
      // Session lives on the Windows side — run claude/codex natively on
      // Windows without bouncing through wsl.exe. Convert /mnt/c/... paths
      // back to C:\ so wt.exe can cd into the project.
      const winProjectDir = toWindowsPath(projectDir);
      if (tid === 'wsl-powershell') {
        const psInner = `$Host.UI.RawUI.WindowTitle='${tag}'; Set-Location -LiteralPath '${(winProjectDir || '.').replace(/'/g, "''")}'; ${cmd}`;
        // execFileSync with an argv array keeps /bin/sh out of the loop so
        // PowerShell variables like $Host survive until the child shell.
        execFileSync('powershell.exe', [
          '-NoProfile',
          '-Command',
          'Start-Process',
          'powershell',
          '-ArgumentList',
          `'-NoExit','-NoProfile','-Command','${psInner.replace(/'/g, "''")}'`,
        ], { stdio: 'pipe' });
      } else {
        // `-w 0` targets the current/MRU window so the session opens as a
        // new tab instead of a new window. wt falls back to creating a
        // fresh window if none exists, so no special handling needed.
        // Focus later selects the right tab via UIA, not MainWindowTitle.
        const args = ['-w', '0', 'new-tab', '--title', tag, '--suppressApplicationTitle'];
        if (winProjectDir) { args.push('--startingDirectory', winProjectDir); }
        args.push('cmd.exe', '/k', cmd);
        execFileSafe('wt.exe', args);
      }
      return;
    }

    // WSL-side session: wrap cd + resume in a .sh so nested quoting through
    // wt.exe / powershell.exe / wsl.exe / bash stays safe.
    const { file: scriptPath, dir: scriptDir } = writeWslLaunchScript(fullCmd);
    const distro = wslDistro();
    const distroArg = distro ? ` -d '${distro.replace(/'/g, "''")}'` : '';

    if (tid === 'wsl-powershell') {
      const psInner = `$Host.UI.RawUI.WindowTitle='${tag}'; wsl.exe${distroArg} -- bash -li ${scriptPath.replace(/'/g, "''")}`;
      execFileSync('powershell.exe', [
        '-NoProfile',
        '-Command',
        'Start-Process',
        'powershell',
        '-ArgumentList',
        `'-NoExit','-NoProfile','-Command','${psInner.replace(/'/g, "''")}'`,
      ], { stdio: 'pipe' });
    } else {
      // `-w 0` — see comment above; reuse the current wt window as a new
      // tab and let UIA-based focus pick the right one later.
      const args = [
        '-w', '0',
        'new-tab',
        '--title', tag,
        '--suppressApplicationTitle',
        'wsl.exe',
      ];
      if (distro) { args.push('-d', distro); }
      args.push('--', 'bash', '-li', scriptPath);
      execFileSafe('wt.exe', args);
    }
    // bash reads the script on startup; 60 s is plenty. fs.rm with recursive
    // wipes the mkdtemp dir, not just the file.
    setTimeout(() => {
      try { fs.rmSync(scriptDir, { recursive: true, force: true }); } catch {}
    }, 60000);
  } else if (platform === 'linux') {
    // terminalId can be a known name or an arbitrary binary path
    const bin = terminalId || 'x-terminal-emulator';
    const baseName = path.basename(bin);
    termLog('TERM', `linux: bin=${bin} baseName=${baseName}`);

    // gnome-terminal uses -- instead of -e
    if (baseName === 'gnome-terminal' || baseName === 'gnome-terminal-server') {
      exec(`${bin} -- bash -c "${fullCmd}; exec bash"`);
    }
    // wezterm uses "start --"
    else if (baseName === 'wezterm' || baseName === 'wezterm-gui') {
      exec(`${bin} start -- bash -c '${fullCmd}; exec bash'`);
    }
    // Generic: most terminals support -e or direct argument
    else {
      exec(`${bin} -e bash -c '${fullCmd}; exec bash'`);
    }
  } else {
    switch (terminalId) {
      case 'powershell':
        exec(`start powershell -NoExit -Command "${fullCmd}"`);
        break;
      case 'windows-terminal':
        exec(`wt new-tab cmd /k "${fullCmd}"`);
        break;
      default:
        exec(`start cmd /k "${fullCmd}"`);
        break;
    }
  }
}

// ── Focus cmux workspace by PID → env var ───────────────────

function focusCmuxWorkspace(pid) {
  if (pid) {
    try {
      const psEnv = execSync(`ps eww -p ${pid} 2>/dev/null`, { encoding: 'utf8', timeout: 2000 });
      const wsMatch = psEnv.match(/CMUX_WORKSPACE_ID=([0-9A-F-]{36})/i);
      if (wsMatch) {
        cmuxExec(`select-workspace --workspace ${wsMatch[1]}`);
        execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
        return { ok: true, terminal: 'cmux' };
      }
    } catch {}
  }
  execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
  return { ok: true, terminal: 'cmux' };
}

// ── WSL: focus a Windows Terminal tab hosting a Linux pid ───
//
// Strategy (established empirically after ruling out title tagging, WT_SESSION
// targeting via `wt.exe -w 0`, and PEB env reading):
//
//  1. Resolve the pts the target process is bound to via /proc/<pid>/fd/*.
//  2. Ask PowerShell to snapshot every wt TabItem (keyed by window hwnd and
//     positional index) through UI Automation — wt exposes them even when the
//     tab isn't active. We avoid UIA RuntimeId because MSDN explicitly warns
//     it's not persistent between calls, and a second PS invocation re-issues
//     fresh ids for the same tab.
//  3. Write an OSC 2 escape (`\e]2;<marker>\a`) straight into the pts; wt
//     renders it via the master side and the tab's UIA Name updates almost
//     instantly.
//  4. Ask PowerShell to poll UIA for a TabItem whose Name == marker, Select()
//     it via the SelectionItem pattern, and SetForegroundWindow on the parent
//     wt window (handling IsIconic → ShowWindowAsync restore).
//  5. Look up the matched tab's (hwnd, index) in the snapshot, write the
//     original Name back through OSC 2 so the marker doesn't linger in the UI.
//
// Fallbacks: if the target process isn't attached to a pts, or the marker
// never appears in UIA (e.g., wt not running, app rewrites the title too
// quickly), we return a no-op result so the UI shows the "click manually"
// hint.

function ptsForPid(pid) {
  for (const fd of [0, 1, 2]) {
    try {
      const link = fs.readlinkSync(`/proc/${pid}/fd/${fd}`);
      if (link && link.startsWith('/dev/pts/')) return link;
    } catch {}
  }
  return '';
}

// Windows Terminal injects WT_SESSION into each tab's env; WSL forwards it
// via WSLENV=WT_SESSION:WT_PROFILE_ID:..., so it lands in /proc/<pid>/environ
// for anything launched from a WT tab. Absence means the process is in
// conhost/OpenConsole (PowerShell window, etc.), which does NOT render as a
// WT tab — using OSC 2 would mutate the real conhost title and break the
// title-based fallback.
function isWtSession(pid) {
  try {
    const env = fs.readFileSync(`/proc/${pid}/environ`, 'utf8');
    return env.split('\0').some((e) => e.startsWith('WT_SESSION='));
  } catch {
    return false;
  }
}

// PS script: one-shot snapshot of every wt TabItem's position and Name.
// Key is (windowHwnd, tabIndex) because UIA RuntimeId is not guaranteed
// stable across PS invocations, whereas tab index within a window is stable
// as long as the user doesn't reorder tabs (and OSC title writes don't).
// Emits pipe-delimited lines so we don't need ConvertFrom-Json on the Node
// side and PS's default JSON escaping doesn't fight with tab titles that
// contain quotes.
const PS_WT_SNAPSHOT = [
  'Add-Type -AssemblyName UIAutomationClient',
  'Add-Type -AssemblyName UIAutomationTypes',
  '$wt = Get-Process WindowsTerminal -ErrorAction SilentlyContinue | Select-Object -First 1',
  "if (-not $wt) { Write-Output 'NOWT'; exit 0 }",
  '$root = [System.Windows.Automation.AutomationElement]::RootElement',
  '$cond = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ProcessIdProperty, $wt.Id)',
  '$wins = $root.FindAll([System.Windows.Automation.TreeScope]::Children, $cond)',
  '$tabCond = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ControlTypeProperty, [System.Windows.Automation.ControlType]::TabItem)',
  'foreach ($w in $wins) {',
  '  $hwnd = $w.Current.NativeWindowHandle',
  '  $tabs = $w.FindAll([System.Windows.Automation.TreeScope]::Descendants, $tabCond)',
  '  for ($i = 0; $i -lt $tabs.Count; $i++) {',
  '    $t = $tabs.Item($i)',
  '    $nameB64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($t.Current.Name))',
  '    Write-Output "TAB|$hwnd|$i|$nameB64"',
  '  }',
  '}',
  "Write-Output 'END'",
  '',
].join('\r\n');

// PS script: poll UIA for a TabItem whose Name == marker, select it, raise
// the parent wt window. Outputs "OK|<hwnd>|<tabIndex>" on success, "NOTFOUND"
// on timeout. Deliberately separate from the snapshot script so the snapshot
// observes the *original* names before we mutate them via OSC. We scan tabs
// positionally (via Item(i)) so we can report the exact index, which is the
// same key the snapshot records.
const PS_WT_FIND_SELECT = [
  'param([Parameter(Mandatory=$true)][string]$Marker)',
  'Add-Type -AssemblyName UIAutomationClient',
  'Add-Type -AssemblyName UIAutomationTypes',
  '$sig = @"',
  'using System;',
  'using System.Runtime.InteropServices;',
  'public class CodedashFg {',
  '  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);',
  '  [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr h, int n);',
  '  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr h);',
  '}',
  '"@',
  'Add-Type -TypeDefinition $sig -ErrorAction SilentlyContinue',
  '$wt = Get-Process WindowsTerminal -ErrorAction SilentlyContinue | Select-Object -First 1',
  "if (-not $wt) { Write-Output 'NOWT'; exit 0 }",
  '$root = [System.Windows.Automation.AutomationElement]::RootElement',
  '$cond = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ProcessIdProperty, $wt.Id)',
  '$wins = $root.FindAll([System.Windows.Automation.TreeScope]::Children, $cond)',
  '$tabCond = New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::ControlTypeProperty, [System.Windows.Automation.ControlType]::TabItem)',
  '$deadline = (Get-Date).AddMilliseconds(2000)',
  'while ((Get-Date) -lt $deadline) {',
  '  foreach ($w in $wins) {',
  '    $hwnd = $w.Current.NativeWindowHandle',
  '    $tabs = $w.FindAll([System.Windows.Automation.TreeScope]::Descendants, $tabCond)',
  '    for ($i = 0; $i -lt $tabs.Count; $i++) {',
  '      $t = $tabs.Item($i)',
  '      if ($t.Current.Name -eq $Marker) {',
  '        try {',
  '          $si = $t.GetCurrentPattern([System.Windows.Automation.SelectionItemPattern]::Pattern)',
  '          $si.Select()',
  '        } catch {}',
  '        $h = [IntPtr]$hwnd',
  '        if ($h -ne [IntPtr]::Zero) {',
  '          if ([CodedashFg]::IsIconic($h)) { [CodedashFg]::ShowWindowAsync($h, 9) | Out-Null }',
  '          [CodedashFg]::SetForegroundWindow($h) | Out-Null',
  '        }',
  '        Write-Output "OK|$hwnd|$i"',
  '        exit 0',
  '      }',
  '    }',
  '  }',
  '  Start-Sleep -Milliseconds 75',
  '}',
  "Write-Output 'NOTFOUND'",
  '',
].join('\r\n');

// PS script: fallback for non-WindowsTerminal processes (powershell.exe,
// conhost/OpenConsole). The launch path pins `$Host.UI.RawUI.WindowTitle` to
// the sessionTag, so an exact MainWindowTitle match is reliable. We exclude
// WindowsTerminal on purpose: WT only exposes the currently active tab via
// MainWindowTitle, so matching it here could focus the wrong tab — the UIA
// path above is the authoritative one for WT.
const PS_WINDOW_BY_TITLE = [
  'param([Parameter(Mandatory=$true)][string]$Tag)',
  '$sig = @"',
  'using System;',
  'using System.Runtime.InteropServices;',
  'public class CodedashWin {',
  '  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);',
  '  [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr h, int n);',
  '  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr h);',
  '}',
  '"@',
  'Add-Type -TypeDefinition $sig -ErrorAction SilentlyContinue',
  '$proc = Get-Process | Where-Object { $_.ProcessName -ne "WindowsTerminal" -and $_.MainWindowTitle -and $_.MainWindowTitle -eq $Tag } | Select-Object -First 1',
  'if ($proc) {',
  '  $h = $proc.MainWindowHandle',
  '  if ([CodedashWin]::IsIconic($h)) { [CodedashWin]::ShowWindowAsync($h, 9) | Out-Null }',
  '  [CodedashWin]::SetForegroundWindow($h) | Out-Null',
  "  Write-Output 'OK'",
  '} else {',
  "  Write-Output 'NOTFOUND'",
  '}',
  '',
].join('\r\n');

let _ps1SnapshotPath = null;
let _ps1FindPath = null;
let _ps1WindowByTitlePath = null;
function ensureFocusScripts() {
  // Reuse a single set of .ps1 files per process — avoids hundreds of stale
  // temp files if the user hammers the Focus button.
  if (!_ps1SnapshotPath) {
    _ps1SnapshotPath = path.join(os.tmpdir(), `codedash-wt-snapshot-${process.pid}.ps1`);
    fs.writeFileSync(_ps1SnapshotPath, PS_WT_SNAPSHOT);
  }
  if (!_ps1FindPath) {
    _ps1FindPath = path.join(os.tmpdir(), `codedash-wt-find-${process.pid}.ps1`);
    fs.writeFileSync(_ps1FindPath, PS_WT_FIND_SELECT);
  }
  if (!_ps1WindowByTitlePath) {
    _ps1WindowByTitlePath = path.join(os.tmpdir(), `codedash-win-by-title-${process.pid}.ps1`);
    fs.writeFileSync(_ps1WindowByTitlePath, PS_WINDOW_BY_TITLE);
  }
  return { snapshot: _ps1SnapshotPath, find: _ps1FindPath, windowByTitle: _ps1WindowByTitlePath };
}

function writeOscTitle(ttyPath, title) {
  // OSC 2 (\e]2;<title>\a) sets the window/tab title. Writing to the slave
  // pts from outside the app flows through to the master side and wt picks
  // it up as if the app itself had emitted it.
  const fd = fs.openSync(ttyPath, 'w');
  try {
    fs.writeSync(fd, `\x1b]2;${title}\x07`);
  } finally {
    fs.closeSync(fd);
  }
}

// Attempt the Windows Terminal UIA + OSC marker path for the given pts.
// Returns the same { ok, terminal, error } shape as focusWslByPid.
function focusWtTabByMarker(tty, scripts) {
  // Snapshot first so we can restore the original tab title afterwards.
  // Key format: "<hwnd>|<tabIndex>" — matches what the find script reports.
  const snapshotMap = new Map();
  try {
    const out = execFileSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', scripts.snapshot],
      { encoding: 'utf8', timeout: 5000 }
    );
    for (const line of out.split(/\r?\n/)) {
      if (!line.startsWith('TAB|')) continue;
      const parts = line.split('|');
      if (parts.length < 4) continue;
      const hwnd = parts[1];
      const idx = parts[2];
      const nameB64 = parts.slice(3).join('|');
      const name = Buffer.from(nameB64, 'base64').toString('utf8');
      snapshotMap.set(`${hwnd}|${idx}`, name);
    }
    termLog('FOCUS', `wt snapshot: ${snapshotMap.size} tab(s)`);
  } catch (e) {
    termLog('ERROR', `wt snapshot failed: ${e.message}`);
    return { ok: false, error: 'wt snapshot failed: ' + e.message };
  }

  if (snapshotMap.size === 0) {
    return { ok: false, error: 'No Windows Terminal tabs visible — is wt running?' };
  }

  // Inject marker into the pts so the target tab renames itself.
  const marker = `codedash-focus-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
  try {
    writeOscTitle(tty, marker);
  } catch (e) {
    termLog('ERROR', `osc write to ${tty} failed: ${e.message}`);
    return { ok: false, error: 'Could not write marker to pts: ' + e.message };
  }

  let matchedKey = '';
  try {
    const out = execFileSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', scripts.find, '-Marker', marker],
      { encoding: 'utf8', timeout: 6000 }
    ).trim();
    termLog('FOCUS', `wt find: ${out}`);
    if (out.startsWith('OK|')) {
      matchedKey = out.slice(3); // "<hwnd>|<tabIndex>"
    } else {
      // Best-effort title cleanup — the marker is still on the tab, so rewrite
      // it to empty and let claude/codex repaint on the next update.
      try { writeOscTitle(tty, ''); } catch {}
      return { ok: false, error: 'wt tab not found' };
    }
  } catch (e) {
    termLog('ERROR', `wt find failed: ${e.message}`);
    try { writeOscTitle(tty, ''); } catch {}
    return { ok: false, error: e.message };
  }

  // Restore the tab's pre-marker title. A missing entry means the tab was
  // created between snapshot and find — fall back to blank so the next agent
  // paint wins.
  const origName = snapshotMap.get(matchedKey);
  termLog('FOCUS', `restore key=${matchedKey} name=${JSON.stringify(origName)}`);
  try {
    writeOscTitle(tty, origName != null ? origName : '');
  } catch (e) {
    termLog('ERROR', `title restore failed: ${e.message}`);
  }

  return { ok: true, terminal: 'Windows Terminal' };
}

// Attempt the non-WT fallback: locate a top-level window whose
// MainWindowTitle exactly equals the sessionTag. This covers the
// `wsl-powershell` launch path, which pins the console window title at
// startup. WindowsTerminal is excluded inside the PS script.
function focusWindowBySessionTag(sessionId, scripts) {
  try {
    assertSafeSessionId(sessionId);
  } catch (e) {
    return { ok: false, error: e.message };
  }
  const tag = sessionTag(sessionId);
  try {
    const out = execFileSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', scripts.windowByTitle, '-Tag', tag],
      { encoding: 'utf8', timeout: 5000 }
    ).trim();
    termLog('FOCUS', `wsl title fallback: ${out}`);
    if (out.endsWith('OK')) return { ok: true, terminal: 'PowerShell' };
    return { ok: false, error: 'Could not focus — try clicking the terminal manually' };
  } catch (e) {
    termLog('ERROR', `wsl title fallback failed: ${e.message}`);
    return { ok: false, error: e.message };
  }
}

function focusWslByPid(pid, sessionId) {
  // Defense in depth: /api/focus also validates, but focusWslByPid feeds pid
  // directly into /proc/<pid>/fd/<n>, so re-check before touching the path.
  if (!Number.isInteger(pid) || pid <= 0) {
    return { ok: false, error: 'invalid pid' };
  }

  let scripts;
  try {
    scripts = ensureFocusScripts();
  } catch (e) {
    termLog('ERROR', `ensureFocusScripts: ${e.message}`);
    return { ok: false, error: e.message };
  }

  // WT_SESSION in /proc/<pid>/environ tells us whether the target actually
  // lives inside a Windows Terminal tab. Gating the WT marker path on this
  // flag is critical: conhost honors OSC 2, so writing the marker into a
  // non-WT pts would overwrite the console's real title and break the
  // sessionTag-based fallback further down.
  const tty = ptsForPid(pid);
  const inWt = tty ? isWtSession(pid) : false;
  termLog('FOCUS', `wsl pid ${pid} pts=${tty || '(none)'} inWt=${inWt}`);

  if (inWt) {
    const wtResult = focusWtTabByMarker(tty, scripts);
    if (wtResult.ok) return wtResult;
    termLog('FOCUS', `wt path failed, trying title fallback: ${wtResult.error || ''}`);
  }

  // Fallback for `wsl-powershell` launches (conhost/powershell.exe windows)
  // that pin MainWindowTitle to sessionTag at startup. Also catches the edge
  // case where WT path missed after pts mutation — title may now be blank,
  // so this will just return NOTFOUND without doing harm.
  if (sessionId) {
    return focusWindowBySessionTag(sessionId, scripts);
  }

  return { ok: false, error: 'Could not focus — try clicking the terminal manually' };
}

// ── Focus existing terminal by PID ──────────────────────────

function focusTerminalByPid(pid, sessionId) {
  const platform = process.platform;
  termLog('FOCUS', `focusTerminalByPid: pid=${pid} sessionId=${sessionId || '(none)'} platform=${platform}`);

  if (platform === 'linux' && isWSL()) {
    return focusWslByPid(pid, sessionId);
  }

  if (platform === 'darwin') {
    // Find which terminal app owns this PID's TTY, then activate it
    try {
      // Get TTY of the process
      const ttyOut = execSync(`ps -p ${pid} -o tty= 2>/dev/null`, { encoding: 'utf8' }).trim();
      termLog('FOCUS', `tty=${ttyOut || '(empty)'}`);
      if (!ttyOut) throw new Error('no tty');

      // Walk parent chain to detect the actual terminal app
      let detectedTerminal = '';
      try {
        let checkPid = pid;
        for (let depth = 0; depth < 6; depth++) {
          const ppid = execSync(`ps -p ${checkPid} -o ppid= 2>/dev/null`, { encoding: 'utf8' }).trim();
          if (!ppid || ppid === '0' || ppid === '1') break;
          const parentCmd = execSync(`ps -p ${ppid} -o comm= 2>/dev/null`, { encoding: 'utf8' }).trim();
          termLog('FOCUS', `parent chain: depth=${depth} ppid=${ppid} cmd=${parentCmd}`);
          if (parentCmd.includes('cmux')) { detectedTerminal = 'cmux'; break; }
          if (parentCmd.includes('iTerm')) { detectedTerminal = 'iTerm2'; break; }
          if (parentCmd.includes('Terminal')) { detectedTerminal = 'Terminal.app'; break; }
          if (parentCmd.includes('Warp')) { detectedTerminal = 'Warp'; break; }
          if (parentCmd.includes('kitty')) { detectedTerminal = 'kitty'; break; }
          if (parentCmd.includes('alacritty')) { detectedTerminal = 'Alacritty'; break; }
          checkPid = ppid;
        }
      } catch {}

      termLog('FOCUS', `detected terminal from parent chain: ${detectedTerminal || '(none)'}`);

      // cmux: select workspace by PID's CMUX_WORKSPACE_ID env var
      if (detectedTerminal === 'cmux') {
        return focusCmuxWorkspace(pid);
      }

      // iTerm2: activate and select the right tab/window/session by tty
      if (detectedTerminal === 'iTerm2' || !detectedTerminal) {
        try {
          // Normalize tty: "ttys005" → "ttys005", "/dev/ttys005" → "ttys005"
          const ttyNorm = ttyOut.replace('/dev/', '');
          const script = `
            tell application "iTerm"
              activate
              repeat with w in windows
                repeat with t in tabs of w
                  repeat with s in sessions of t
                    set sessionTTY to tty of s
                    if sessionTTY contains "${ttyNorm}" then
                      select w
                      tell w to select t
                      tell t to select s
                      return "found"
                    end if
                  end repeat
                end repeat
              end repeat
            end tell
            return "not found"
          `;
          const result = execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { encoding: 'utf8', timeout: 3000 }).trim();
          if (result === 'found') {
            return { ok: true, terminal: 'iTerm2' };
          }
          // If we specifically detected iTerm2 but couldn't find the tab, still activate it
          if (detectedTerminal === 'iTerm2') {
            return { ok: true, terminal: 'iTerm2' };
          }
        } catch {}
      }

      // Terminal.app: activate and select the right window by tty
      if (detectedTerminal === 'Terminal.app' || !detectedTerminal) {
        try {
          const script = `
            tell application "Terminal"
              activate
              repeat with w in windows
                repeat with t in tabs of w
                  if tty of t contains "${ttyOut}" or "${ttyOut}" contains tty of t then
                    set selected tab of w to t
                    set index of w to 1
                    return "found"
                  end if
                end repeat
              end repeat
            end tell
            return "not found"
          `;
          execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { encoding: 'utf8', timeout: 3000 });
          return { ok: true, terminal: 'Terminal.app' };
        } catch {}
      }

      // Warp
      if (detectedTerminal === 'Warp') {
        try {
          execSync(`osascript -e 'tell application "Warp" to activate'`, { stdio: 'pipe', timeout: 2000 });
          return { ok: true, terminal: 'Warp' };
        } catch {}
      }

      // Fallback: activate whatever terminal we detected, or try both
      if (detectedTerminal) {
        try {
          execSync(`osascript -e 'tell application "${detectedTerminal}" to activate'`, { stdio: 'pipe' });
          return { ok: true, terminal: detectedTerminal };
        } catch {}
      }
      try {
        execSync(`osascript -e 'tell application "iTerm" to activate'`, { stdio: 'pipe' });
        return { ok: true, terminal: 'iTerm2' };
      } catch {}
      try {
        execSync(`osascript -e 'tell application "Terminal" to activate'`, { stdio: 'pipe' });
        return { ok: true, terminal: 'Terminal.app' };
      } catch {}
    } catch {}
  }

  // Linux: use WINDOWID from /proc for precise window matching,
  // terminal-specific APIs for tab-level focus, wmctrl/xdotool as fallback
  if (platform === 'linux') {
    try {
      const pidChain = [];
      let walkPid = String(pid);
      let windowId = null;
      let detectedTerminal = '';
      const knownTerminals = ['gnome-terminal', 'konsole', 'kitty', 'alacritty', 'xterm',
        'terminator', 'tilix', 'xfce4-terminal', 'mate-terminal', 'wezterm', 'foot', 'st', 'urxvt'];

      // Walk parent chain: collect PIDs, find WINDOWID, detect terminal
      for (let depth = 0; depth < 20; depth++) {
        pidChain.push(walkPid);

        // Read WINDOWID from /proc/<pid>/environ (set by terminal emulators)
        if (!windowId) {
          try {
            const envData = fs.readFileSync(`/proc/${walkPid}/environ`);
            const vars = envData.toString('utf8').split('\0');
            for (const v of vars) {
              if (v.startsWith('WINDOWID=')) {
                windowId = v.slice(9);
                break;
              }
            }
          } catch {}
        }

        // Detect terminal name from process command
        if (!detectedTerminal) {
          try {
            const cmd = execSync(`ps -p ${walkPid} -o comm= 2>/dev/null`, { encoding: 'utf8' }).trim();
            for (const name of knownTerminals) {
              if (cmd.includes(name)) { detectedTerminal = name; break; }
            }
          } catch {}
        }

        try {
          const ppid = execSync(`ps -p ${walkPid} -o ppid= 2>/dev/null`, { encoding: 'utf8' }).trim();
          if (!ppid || ppid === '0' || ppid === '1') break;
          walkPid = ppid;
        } catch { break; }
      }

      termLog('FOCUS', `linux: windowId=${windowId || 'none'} terminal=${detectedTerminal || 'none'} chain=${pidChain.length} pids`);

      // ── Terminal-specific tab focus (works at tab level, not just window) ──

      if (detectedTerminal === 'kitty') {
        try {
          execSync(`kitty @ focus-window --match pid:${pid}`, { stdio: 'pipe', timeout: 2000 });
          termLog('FOCUS', 'kitty remote control: focused by pid');
          return { ok: true, terminal: 'kitty' };
        } catch {
          termLog('FOCUS', 'kitty remote control failed (enable allow_remote_control), falling back');
        }
      }

      // ── Focus by WINDOWID (precise — each tab gets its own WINDOWID) ──

      if (windowId && windowId !== '0') {
        termLog('FOCUS', `trying WINDOWID=${windowId}`);

        // xdotool accepts decimal WINDOWID directly
        try {
          execSync(`xdotool windowactivate ${windowId}`, { stdio: 'pipe', timeout: 2000 });
          termLog('FOCUS', `xdotool focused WINDOWID=${windowId}`);
          return { ok: true, terminal: detectedTerminal || 'linux' };
        } catch {}

        // wmctrl needs hex format
        try {
          const hexId = '0x' + parseInt(windowId, 10).toString(16).padStart(8, '0');
          execSync(`wmctrl -ia ${hexId}`, { stdio: 'pipe', timeout: 2000 });
          termLog('FOCUS', `wmctrl focused WINDOWID=${hexId}`);
          return { ok: true, terminal: detectedTerminal || 'linux' };
        } catch {}
      }

      // ── Fallback: match PID chain against wmctrl window list ──

      try {
        const windows = execSync('wmctrl -l -p 2>/dev/null', { encoding: 'utf8' });
        for (const line of windows.split('\n')) {
          const parts = line.trim().split(/\s+/);
          if (parts.length >= 3 && pidChain.includes(parts[2])) {
            execSync(`wmctrl -ia ${parts[0]}`, { stdio: 'pipe' });
            termLog('FOCUS', `wmctrl pid-match focused ${parts[0]}`);
            return { ok: true, terminal: detectedTerminal || 'linux' };
          }
        }
      } catch {}

      // ── Last resort: xdotool search by PID ──

      try {
        for (const p of pidChain) {
          const wids = execSync(`xdotool search --pid ${p} 2>/dev/null`, { encoding: 'utf8' }).trim();
          if (wids) {
            const wid = wids.split('\n')[0];
            execSync(`xdotool windowactivate ${wid}`, { stdio: 'pipe' });
            termLog('FOCUS', `xdotool pid-search focused ${wid}`);
            return { ok: true, terminal: detectedTerminal || 'linux' };
          }
        }
      } catch {}
    } catch {}
  }

  return { ok: false };
}

module.exports = { detectTerminals, openInTerminal, focusTerminalByPid, isWSL };
