'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync, execFileSync, exec, execFile } = require('child_process');

function execFileSafe(cmd, args) {
  // Fire-and-forget: wt.exe / powershell.exe detach immediately, we only care
  // that the Windows process was kicked off. Errors are logged, never thrown.
  execFile(cmd, args, (err) => {
    if (err) termLog('ERROR', `${cmd} failed: ${err.message}`);
  });
}

// Run cmux CLI command via osascript — needed because codedash runs as a detached server
// and cmux rejects direct socket connections from processes not inside a cmux terminal
function cmuxExec(args) {
  const escaped = args.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return execSync(`osascript -e 'do shell script "cmux ${escaped}"'`, { encoding: 'utf8', timeout: 5000 }).trim();
}

// ── WSL detection ───────────────────────────────────────────

let _wslCache = null;
function isWSL() {
  if (_wslCache !== null) return _wslCache;
  if (process.platform !== 'linux') { _wslCache = false; return false; }
  if (process.env.WSL_DISTRO_NAME || process.env.WSL_INTEROP) { _wslCache = true; return true; }
  try {
    const v = fs.readFileSync('/proc/version', 'utf8');
    _wslCache = /microsoft|WSL/i.test(v);
  } catch { _wslCache = false; }
  return _wslCache;
}

function wslDistro() {
  return process.env.WSL_DISTRO_NAME || '';
}

// Tag used as tab/window title so focusTerminalByPid can locate the window later.
function sessionTag(sessionId) {
  return 'codedash-' + String(sessionId || '').slice(0, 12);
}

// A session is "Windows-side" if its cwd looks like a Windows path
// (drive letter or backslashes) or lives under /mnt/<drive>/... from WSL.
function isWindowsSidePath(p) {
  if (!p) return false;
  if (/^[A-Za-z]:[\\/]/.test(p)) return true;
  if (p.includes('\\')) return true;
  if (/^\/mnt\/[a-z]\//i.test(p)) return true;
  return false;
}

// Translate /mnt/c/Users/foo → C:\Users\foo. Windows-format paths pass through.
function toWindowsPath(p) {
  if (!p) return '';
  if (/^[A-Za-z]:[\\/]/.test(p) || p.includes('\\')) return p.replace(/\//g, '\\');
  const m = p.match(/^\/mnt\/([a-z])\/(.*)$/i);
  if (m) return m[1].toUpperCase() + ':\\' + m[2].replace(/\//g, '\\');
  try {
    return execSync(`wslpath -w ${JSON.stringify(p)}`, { encoding: 'utf8', timeout: 2000 }).trim();
  } catch {
    return p;
  }
}

// Write the resume command to a temp .sh file to avoid nested quoting through
// wt.exe / cmd.exe / powershell.exe / wsl.exe / bash.
function writeWslLaunchScript(sessionId, fullCmd) {
  const dir = os.tmpdir();
  const file = path.join(dir, `codedash-launch-${sessionId || Date.now()}.sh`);
  const body = [
    '#!/bin/bash',
    '# Auto-generated by codedash — safe to delete',
    fullCmd,
    'echo',
    'echo "[codedash] session finished — press Enter to close, or keep this shell."',
    'exec bash -l',
    '',
  ].join('\n');
  fs.writeFileSync(file, body, { mode: 0o755 });
  return file;
}

// ── Detect available terminals ──────────────────────────────

function detectTerminals() {
  const terminals = [];
  const platform = process.platform;

  if (platform === 'darwin') {
    // Check iTerm2
    try {
      execSync('osascript -e \'application id "com.googlecode.iterm2"\'', { stdio: 'pipe' });
      terminals.push({ id: 'iterm2', name: 'iTerm2', available: true });
    } catch {
      terminals.push({ id: 'iterm2', name: 'iTerm2', available: false });
    }
    // Terminal.app always available on macOS
    terminals.push({ id: 'terminal', name: 'Terminal.app', available: true });
    // Check Warp
    try {
      const warpInstalled = fs.existsSync('/Applications/Warp.app');
      terminals.push({ id: 'warp', name: 'Warp', available: warpInstalled });
    } catch {
      terminals.push({ id: 'warp', name: 'Warp', available: false });
    }
    // Check Kitty
    try {
      execSync('which kitty', { stdio: 'pipe' });
      terminals.push({ id: 'kitty', name: 'Kitty', available: true });
    } catch {}
    // Check Alacritty
    try {
      execSync('which alacritty', { stdio: 'pipe' });
      terminals.push({ id: 'alacritty', name: 'Alacritty', available: true });
    } catch {}
    // Check cmux
    try {
      if (fs.existsSync('/Applications/cmux.app')) {
        terminals.push({ id: 'cmux', name: 'cmux', available: true });
      }
    } catch {}
  } else if (platform === 'linux' && isWSL()) {
    // WSL: launch Windows-side terminals via wsl.exe so the UI in the Windows
    // browser can spawn a new console on the host and keep the CLI agent in WSL.
    const wslTerms = [
      { id: 'wsl-windows-terminal', name: 'Windows Terminal (wt.exe)', cmd: 'wt.exe' },
      { id: 'wsl-powershell', name: 'PowerShell (powershell.exe)', cmd: 'powershell.exe' },
    ];
    for (const t of wslTerms) {
      try {
        execSync(`which ${t.cmd}`, { stdio: 'pipe' });
        terminals.push({ id: t.id, name: t.name, available: true });
      } catch {
        terminals.push({ id: t.id, name: t.name, available: false });
      }
    }
  } else if (platform === 'linux') {
    const linuxTerms = [
      { id: 'gnome-terminal', name: 'GNOME Terminal', cmd: 'gnome-terminal' },
      { id: 'konsole', name: 'Konsole', cmd: 'konsole' },
      { id: 'kitty', name: 'Kitty', cmd: 'kitty' },
      { id: 'alacritty', name: 'Alacritty', cmd: 'alacritty' },
      { id: 'xterm', name: 'xterm', cmd: 'xterm' },
    ];
    for (const t of linuxTerms) {
      try {
        execSync(`which ${t.cmd}`, { stdio: 'pipe' });
        terminals.push({ ...t, available: true });
      } catch {
        terminals.push({ ...t, available: false });
      }
    }
  } else {
    terminals.push({ id: 'cmd', name: 'Command Prompt', available: true });
    terminals.push({ id: 'powershell', name: 'PowerShell', available: true });
    try {
      execSync('where wt', { stdio: 'pipe' });
      terminals.push({ id: 'windows-terminal', name: 'Windows Terminal', available: true });
    } catch {}
  }

  return terminals;
}

// ── Terminal launch ─────────────────────────────────────────

function termLog(tag, msg) {
  const ts = new Date().toLocaleTimeString('en-GB');
  const color = tag === 'ERROR' ? '\x1b[31m' : '\x1b[35m';
  console.log(`  ${color}${ts} [${tag}]\x1b[0m ${msg}`);
}

function openInTerminal(sessionId, tool, flags, projectDir, terminalId) {
  const skipPerms = flags.includes('skip-permissions');
  let cmd;

  if (tool === 'codex') {
    cmd = `codex resume ${sessionId}`;
  } else {
    cmd = `claude --resume ${sessionId}`;
    if (skipPerms) cmd += ' --dangerously-skip-permissions';
  }

  const cdPart = projectDir ? `cd ${JSON.stringify(projectDir)} && ` : '';
  const fullCmd = cdPart + cmd;
  const escapedCmd = fullCmd.replace(/"/g, '\\"');
  termLog('TERM', `openInTerminal: terminal=${terminalId || 'default'} tool=${tool} cmd="${fullCmd}"`);

  const platform = process.platform;

  if (platform === 'darwin') {
    switch (terminalId) {
      case 'terminal':
        execSync(`osascript -e 'tell application "Terminal"
          activate
          do script "${escapedCmd}"
        end tell'`);
        break;
      case 'warp': {
        // Warp Launch Configurations API — write temp YAML, open via URI scheme
        const warpConfigDir = path.join(os.homedir(), '.warp', 'launch_configurations');
        const warpConfigName = `codedash-${Date.now()}`;
        const warpConfigPath = path.join(warpConfigDir, `${warpConfigName}.yaml`);
        fs.mkdirSync(warpConfigDir, { recursive: true });
        const warpYaml = [
          '---',
          `name: ${warpConfigName}`,
          'windows:',
          '  - tabs:',
          '      - layout:',
          `          cwd: "${projectDir || ''}"`,
          '          commands:',
          `            - exec: "${cmd.replace(/"/g, '\\"')}"`,
        ].join('\n') + '\n';
        fs.writeFileSync(warpConfigPath, warpYaml);
        try {
          execSync(`open "warp://launch/${warpConfigName}"`, { stdio: 'pipe', timeout: 3000 });
        } catch {
          // Fallback to Terminal.app
          execSync(`osascript -e 'tell application "Terminal" to do script "${escapedCmd}"'`);
        }
        setTimeout(() => { try { fs.unlinkSync(warpConfigPath); } catch {} }, 3000);
        break;
      }
      case 'kitty':
        exec(`kitty --single-instance bash -c '${fullCmd}; exec bash'`);
        break;
      case 'alacritty':
        exec(`alacritty -e bash -c '${fullCmd}; exec bash'`);
        break;
      case 'cmux': {
        // cmux — open new workspace with resume command, then switch to it
        try {
          const cwdArg = projectDir ? ` --cwd ${JSON.stringify(projectDir)}` : '';
          const cmdArg = ` --command ${JSON.stringify(cmd)}`;
          const out = cmuxExec(`new-workspace${cwdArg}${cmdArg}`);
          const wsMatch = out.match(/workspace:\d+/);
          if (wsMatch) {
            cmuxExec(`select-workspace --workspace ${wsMatch[0]}`);
          }
          execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
        } catch {
          execSync(`osascript -e 'tell application "cmux" to activate'`);
        }
        break;
      }
      case 'iterm2':
      default: {
        const script = `
          tell application "iTerm"
            activate
            set newWindow to (create window with default profile)
            tell current session of newWindow
              write text "${escapedCmd}"
            end tell
          end tell
        `;
        try {
          execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { stdio: 'pipe' });
        } catch {
          // Fallback to Terminal.app
          execSync(`osascript -e 'tell application "Terminal" to do script "${escapedCmd}"'`);
        }
        break;
      }
    }
  } else if (platform === 'linux' && isWSL()) {
    const tag = sessionTag(sessionId);
    const tid = terminalId || 'wsl-windows-terminal';
    const winSide = isWindowsSidePath(projectDir);
    termLog('TERM', `WSL launch: winSide=${winSide} terminal=${tid}`);

    if (winSide) {
      // Session lives on the Windows side — run claude/codex natively on Windows
      // without bouncing through wsl.exe. Convert /mnt/c/... paths back to C:\...
      // so wt.exe can cd into the project.
      const winProjectDir = toWindowsPath(projectDir);
      if (tid === 'wsl-powershell') {
        const psInner = `$Host.UI.RawUI.WindowTitle='${tag}'; Set-Location -LiteralPath '${(winProjectDir || '.').replace(/'/g, "''")}'; ${cmd}`;
        const psCmd = `Start-Process powershell -ArgumentList '-NoExit','-NoProfile','-Command','${psInner.replace(/'/g, "''")}'`;
        execSync(`powershell.exe -NoProfile -Command ${JSON.stringify(psCmd)}`, { stdio: 'pipe' });
      } else {
        const args = ['-w', '0', 'new-tab', '--title', tag, '--suppressApplicationTitle'];
        if (winProjectDir) { args.push('--startingDirectory', winProjectDir); }
        args.push('cmd.exe', '/k', cmd);
        execFileSafe('wt.exe', args);
      }
      return;
    }

    // WSL-side session: wrap cd + resume in a .sh so nested quoting through
    // wt.exe / powershell.exe / wsl.exe / bash stays safe.
    const scriptPath = writeWslLaunchScript(sessionId, fullCmd);
    const distro = wslDistro();
    const distroArg = distro ? ` -d ${JSON.stringify(distro)}` : '';

    if (tid === 'wsl-powershell') {
      const psInner = `$Host.UI.RawUI.WindowTitle='${tag}'; wsl.exe${distroArg} -- bash ${scriptPath.replace(/'/g, "''")}`;
      const psCmd = `Start-Process powershell -ArgumentList '-NoExit','-NoProfile','-Command','${psInner.replace(/'/g, "''")}'`;
      execSync(`powershell.exe -NoProfile -Command ${JSON.stringify(psCmd)}`, { stdio: 'pipe' });
    } else {
      const args = [
        '-w', '0',
        'new-tab',
        '--title', tag,
        '--suppressApplicationTitle',
        'wsl.exe',
      ];
      if (distro) { args.push('-d', distro); }
      args.push('--', 'bash', scriptPath);
      execFileSafe('wt.exe', args);
    }
    setTimeout(() => { try { fs.unlinkSync(scriptPath); } catch {} }, 60000);
  } else if (platform === 'linux') {
    switch (terminalId) {
      case 'kitty':
        exec(`kitty bash -c '${fullCmd}; exec bash'`);
        break;
      case 'alacritty':
        exec(`alacritty -e bash -c '${fullCmd}; exec bash'`);
        break;
      case 'konsole':
        exec(`konsole -e bash -c '${fullCmd}; exec bash'`);
        break;
      case 'xterm':
        exec(`xterm -e bash -c '${fullCmd}; exec bash'`);
        break;
      case 'gnome-terminal':
      default:
        exec(`gnome-terminal -- bash -c "${fullCmd}; exec bash"`);
        break;
    }
  } else {
    switch (terminalId) {
      case 'powershell':
        exec(`start powershell -NoExit -Command "${fullCmd}"`);
        break;
      case 'windows-terminal':
        exec(`wt new-tab cmd /k "${fullCmd}"`);
        break;
      default:
        exec(`start cmd /k "${fullCmd}"`);
        break;
    }
  }
}

// ── Focus cmux workspace by PID → env var ───────────────────

function focusCmuxWorkspace(pid) {
  if (pid) {
    try {
      const psEnv = execSync(`ps eww -p ${pid} 2>/dev/null`, { encoding: 'utf8', timeout: 2000 });
      const wsMatch = psEnv.match(/CMUX_WORKSPACE_ID=([0-9A-F-]{36})/i);
      if (wsMatch) {
        cmuxExec(`select-workspace --workspace ${wsMatch[1]}`);
        execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
        return { ok: true, terminal: 'cmux' };
      }
    } catch {}
  }
  execSync(`osascript -e 'tell application "cmux" to activate'`, { stdio: 'pipe', timeout: 2000 });
  return { ok: true, terminal: 'cmux' };
}

// ── Focus existing terminal by PID ──────────────────────────

function focusTerminalByPid(pid, sessionId) {
  const platform = process.platform;
  termLog('FOCUS', `focusTerminalByPid: pid=${pid} sessionId=${sessionId || '(none)'} platform=${platform}`);

  if (platform === 'linux' && isWSL()) {
    // On WSL we launched terminals with a window/tab title tag tied to the
    // session id. Enumerate Windows processes and SetForegroundWindow on the
    // first match whose MainWindowTitle contains the tag.
    if (!sessionId) return { ok: false, error: 'WSL focus requires sessionId' };
    const tag = sessionTag(sessionId);
    // Write a .ps1 script to a temp file — Node's exec runs through /bin/sh,
    // which would otherwise expand PowerShell variables like $p and $t.
    const psBody = [
      'param([Parameter(Mandatory=$true)][string]$Tag)',
      '$sig = @"',
      'using System;',
      'using System.Runtime.InteropServices;',
      'public class CodedashWin {',
      '  [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr h);',
      '  [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr h, int n);',
      '  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr h);',
      '}',
      '"@',
      'Add-Type -TypeDefinition $sig -ErrorAction SilentlyContinue',
      '$proc = Get-Process | Where-Object { $_.MainWindowTitle -and $_.MainWindowTitle -like "*$Tag*" } | Select-Object -First 1',
      'if ($proc) {',
      '  if ([CodedashWin]::IsIconic($proc.MainWindowHandle)) { [CodedashWin]::ShowWindowAsync($proc.MainWindowHandle, 9) | Out-Null }',
      '  [CodedashWin]::SetForegroundWindow($proc.MainWindowHandle) | Out-Null',
      "  Write-Output 'ok'",
      '} else {',
      "  Write-Output 'notfound'",
      '}',
      '',
    ].join('\r\n');
    const ps1Path = path.join(os.tmpdir(), `codedash-focus-${Date.now()}.ps1`);
    try {
      fs.writeFileSync(ps1Path, psBody);
      const out = execFileSync(
        'powershell.exe',
        ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', ps1Path, '-Tag', tag],
        { encoding: 'utf8', timeout: 5000 }
      ).trim();
      termLog('FOCUS', `wsl result: ${out}`);
      if (out.endsWith('ok')) return { ok: true, terminal: 'Windows Terminal / PowerShell' };
      return { ok: false, error: 'Window not found — launch the session from UI first' };
    } catch (e) {
      termLog('ERROR', `wsl focus failed: ${e.message}`);
      return { ok: false, error: e.message };
    } finally {
      try { fs.unlinkSync(ps1Path); } catch {}
    }
  }

  if (platform === 'darwin') {
    // Find which terminal app owns this PID's TTY, then activate it
    try {
      // Get TTY of the process
      const ttyOut = execSync(`ps -p ${pid} -o tty= 2>/dev/null`, { encoding: 'utf8' }).trim();
      termLog('FOCUS', `tty=${ttyOut || '(empty)'}`);
      if (!ttyOut) throw new Error('no tty');

      // Walk parent chain to detect the actual terminal app
      let detectedTerminal = '';
      try {
        let checkPid = pid;
        for (let depth = 0; depth < 6; depth++) {
          const ppid = execSync(`ps -p ${checkPid} -o ppid= 2>/dev/null`, { encoding: 'utf8' }).trim();
          if (!ppid || ppid === '0' || ppid === '1') break;
          const parentCmd = execSync(`ps -p ${ppid} -o comm= 2>/dev/null`, { encoding: 'utf8' }).trim();
          termLog('FOCUS', `parent chain: depth=${depth} ppid=${ppid} cmd=${parentCmd}`);
          if (parentCmd.includes('cmux')) { detectedTerminal = 'cmux'; break; }
          if (parentCmd.includes('iTerm')) { detectedTerminal = 'iTerm2'; break; }
          if (parentCmd.includes('Terminal')) { detectedTerminal = 'Terminal.app'; break; }
          if (parentCmd.includes('Warp')) { detectedTerminal = 'Warp'; break; }
          if (parentCmd.includes('kitty')) { detectedTerminal = 'kitty'; break; }
          if (parentCmd.includes('alacritty')) { detectedTerminal = 'Alacritty'; break; }
          checkPid = ppid;
        }
      } catch {}

      termLog('FOCUS', `detected terminal from parent chain: ${detectedTerminal || '(none)'}`);

      // cmux: select workspace by PID's CMUX_WORKSPACE_ID env var
      if (detectedTerminal === 'cmux') {
        return focusCmuxWorkspace(pid);
      }

      // iTerm2: activate and select the right tab/window/session by tty
      if (detectedTerminal === 'iTerm2' || !detectedTerminal) {
        try {
          // Normalize tty: "ttys005" → "ttys005", "/dev/ttys005" → "ttys005"
          const ttyNorm = ttyOut.replace('/dev/', '');
          const script = `
            tell application "iTerm"
              activate
              repeat with w in windows
                repeat with t in tabs of w
                  repeat with s in sessions of t
                    set sessionTTY to tty of s
                    if sessionTTY contains "${ttyNorm}" then
                      select w
                      tell w to select t
                      tell t to select s
                      return "found"
                    end if
                  end repeat
                end repeat
              end repeat
            end tell
            return "not found"
          `;
          const result = execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { encoding: 'utf8', timeout: 3000 }).trim();
          if (result === 'found') {
            return { ok: true, terminal: 'iTerm2' };
          }
          // If we specifically detected iTerm2 but couldn't find the tab, still activate it
          if (detectedTerminal === 'iTerm2') {
            return { ok: true, terminal: 'iTerm2' };
          }
        } catch {}
      }

      // Terminal.app: activate and select the right window by tty
      if (detectedTerminal === 'Terminal.app' || !detectedTerminal) {
        try {
          const script = `
            tell application "Terminal"
              activate
              repeat with w in windows
                repeat with t in tabs of w
                  if tty of t contains "${ttyOut}" or "${ttyOut}" contains tty of t then
                    set selected tab of w to t
                    set index of w to 1
                    return "found"
                  end if
                end repeat
              end repeat
            end tell
            return "not found"
          `;
          execSync(`osascript -e '${script.replace(/'/g, "'\\''")}'`, { encoding: 'utf8', timeout: 3000 });
          return { ok: true, terminal: 'Terminal.app' };
        } catch {}
      }

      // Warp
      if (detectedTerminal === 'Warp') {
        try {
          execSync(`osascript -e 'tell application "Warp" to activate'`, { stdio: 'pipe', timeout: 2000 });
          return { ok: true, terminal: 'Warp' };
        } catch {}
      }

      // Fallback: activate whatever terminal we detected, or try both
      if (detectedTerminal) {
        try {
          execSync(`osascript -e 'tell application "${detectedTerminal}" to activate'`, { stdio: 'pipe' });
          return { ok: true, terminal: detectedTerminal };
        } catch {}
      }
      try {
        execSync(`osascript -e 'tell application "iTerm" to activate'`, { stdio: 'pipe' });
        return { ok: true, terminal: 'iTerm2' };
      } catch {}
      try {
        execSync(`osascript -e 'tell application "Terminal" to activate'`, { stdio: 'pipe' });
        return { ok: true, terminal: 'Terminal.app' };
      } catch {}
    } catch {}
  }

  // Linux/other: not much we can do without window manager integration
  return { ok: false };
}

module.exports = { detectTerminals, openInTerminal, focusTerminalByPid, isWSL };
